This notebook compares the performance between pandas.Series.isin() function and a custom function using Python sets and pandas apply function

In [5]:
import pandas as pd
import lib.io_ as io

In [6]:
%%time
MB_rec_gid = pd.read_parquet('warehouse/MB_tables/recording_gid.parquet')
MB_rec_gid.set_index('gid', inplace=True)

CPU times: user 9.38 s, sys: 4 s, total: 13.4 s
Wall time: 13.3 s

In [7]:
df = io.load_path_file('warehouse/samples/random_file_paths.txt')
df

,timestamp,artist_MBID,release_MBID,recording_MBID
0,1108412731,f4a31f0a-51dd-4fa7-986d-3095c40c5ed9,426c5c82-4472-4f7d-b1d9-9f928d338340,1deb956c-5439-4fbb-b026-5adb4330a934
1,1108422818,db999c3f-f243-4a5f-88d6-0c25243b6661,6079df6b-2c00-4fd6-b015-0e303eedf4fd,14e9eb4e-155d-46ff-9a83-a8d5e1936c81
2,1108423325,ce58d854-7430-4231-aa44-97f0144b3372,e427c52c-60f4-3df4-9493-2df0734d85aa,eced9a9b-cd59-40f8-a580-f27094bd8a89
3,1108428897,ce58d854-7430-4231-aa44-97f0144b3372,e427c52c-60f4-3df4-9493-2df0734d85aa,eced9a9b-cd59-40f8-a580-f27094bd8a89
4,1108429140,ce58d854-7430-4231-aa44-97f0144b3372,e427c52c-60f4-3df4-9493-2df0734d85aa,eced9a9b-cd59-40f8-a580-f27094bd8a89
...,...,...,...,...
4738134,1357226253,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,81c31179-2457-4036-97d6-5e0cacd191f4
4738135,1374411836,20e8f73a-23b5-4553-ae0e-8e1764b8ce4e,NaN,NaN
4738136,1374412058,NaN,NaN,NaN
4738137,1374412325,NaN,NaN,NaN
4738138,1374412589,NaN,NaN,NaN

# Method 1: pandas.Series.isin()

In [8]:
%%time

df[df.recording_MBID.isin(MB_rec_gid.index)]

CPU times: user 12.6 s, sys: 528 ms, total: 13.1 s
Wall time: 13 s

,timestamp,artist_MBID,release_MBID,recording_MBID
0,1108412731,f4a31f0a-51dd-4fa7-986d-3095c40c5ed9,426c5c82-4472-4f7d-b1d9-9f928d338340,1deb956c-5439-4fbb-b026-5adb4330a934
1,1108422818,db999c3f-f243-4a5f-88d6-0c25243b6661,6079df6b-2c00-4fd6-b015-0e303eedf4fd,14e9eb4e-155d-46ff-9a83-a8d5e1936c81
6,1108679759,3c0a0074-4f26-4d3b-b723-a66bf6cc3753,2af153dd-ad5c-4e73-9587-cc0575a58ba3,06a5b648-0950-4892-a975-715291a5de6f
8,1108680722,a74b1b7f-71a5-4011-9441-d0b5e4122711,NaN,5ef2533b-f50d-426d-829a-93186ff83536
9,1109194759,951d2103-9c7d-4849-ae60-88bf6aa4790b,0b8dc58a-ba86-4915-a0ce-6c5ce8dd7a57,24918272-d403-447c-97c3-e9f115a84360
...,...,...,...,...
4738127,1353764503,2944824d-4c26-476f-a981-be849081942f,41ada184-f564-4d4c-9b52-1c3e64e8beb6,a6eb7554-5255-4221-8223-69ff4763b9dd
4738128,1353764763,2944824d-4c26-476f-a981-be849081942f,41ada184-f564-4d4c-9b52-1c3e64e8beb6,a6eb7554-5255-4221-8223-69ff4763b9dd
4738129,1357225057,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,4933dcd1-ec5e-4976-a2c0-f103150b5bc4
4738130,1357225263,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,eeef1faa-8c26-4942-a0cc-5db530323121
4738132,1357225778,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,972df400-4a04-45b4-a4f7-39892da628b7

# Method 2: Using sets and for loop

In [9]:
%%time
rec_gid_set = set(MB_rec_gid.index)

CPU times: user 6 s, sys: 594 ms, total: 6.59 s
Wall time: 6.53 s

In [11]:
%%time
boolean_map = []
for mbid in df.recording_MBID:
    boolean_map.append(mbid in rec_gid_set)

CPU times: user 997 ms, sys: 14.6 ms, total: 1.01 s
Wall time: 1.01 s

# Method 3: Using sets and apply function

In [12]:
%%time
df[df.recording_MBID.apply(lambda x: x in rec_gid_set)]

CPU times: user 970 ms, sys: 61.2 ms, total: 1.03 s
Wall time: 1.03 s

,timestamp,artist_MBID,release_MBID,recording_MBID
0,1108412731,f4a31f0a-51dd-4fa7-986d-3095c40c5ed9,426c5c82-4472-4f7d-b1d9-9f928d338340,1deb956c-5439-4fbb-b026-5adb4330a934
1,1108422818,db999c3f-f243-4a5f-88d6-0c25243b6661,6079df6b-2c00-4fd6-b015-0e303eedf4fd,14e9eb4e-155d-46ff-9a83-a8d5e1936c81
6,1108679759,3c0a0074-4f26-4d3b-b723-a66bf6cc3753,2af153dd-ad5c-4e73-9587-cc0575a58ba3,06a5b648-0950-4892-a975-715291a5de6f
8,1108680722,a74b1b7f-71a5-4011-9441-d0b5e4122711,NaN,5ef2533b-f50d-426d-829a-93186ff83536
9,1109194759,951d2103-9c7d-4849-ae60-88bf6aa4790b,0b8dc58a-ba86-4915-a0ce-6c5ce8dd7a57,24918272-d403-447c-97c3-e9f115a84360
...,...,...,...,...
4738127,1353764503,2944824d-4c26-476f-a981-be849081942f,41ada184-f564-4d4c-9b52-1c3e64e8beb6,a6eb7554-5255-4221-8223-69ff4763b9dd
4738128,1353764763,2944824d-4c26-476f-a981-be849081942f,41ada184-f564-4d4c-9b52-1c3e64e8beb6,a6eb7554-5255-4221-8223-69ff4763b9dd
4738129,1357225057,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,4933dcd1-ec5e-4976-a2c0-f103150b5bc4
4738130,1357225263,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,eeef1faa-8c26-4942-a0cc-5db530323121
4738132,1357225778,148d7e7c-3557-4738-b594-8fef13fd7668,NaN,972df400-4a04-45b4-a4f7-39892da628b7